### ISSUE TITLE
How to generate camera.npz from Scannet Dataset?

### ISSUE THREAD

**Issue by saulgooodman** [shawLyu/Occ-SDF-Hybrid#3]
Hello, I tried to test the code on scannet dataset but something went wrong. I downloaded the scannet dataset according to official instruction from Scannet and then started to run the Occ-SDF-hybrid code. However, I found that the code needs a camera.npz file. May I ask what is contained in this camera.npz file? BTW, how to obtain this camera.npz file?
The picture given below is the error posted by the complier and the orignal version of scannet dataset. Could you please tell me what to do next. Thanks!
![image](https://github.com/shawLyu/Occ-SDF-Hybrid/assets/91330822/d745e46a-78c8-46f2-bb98-8205bceeed2d)
![image](https://github.com/shawLyu/Occ-SDF-Hybrid/assets/91330822/86691a83-57d3-4441-b836-400a042cd82b)

**Comment by shawLyu** [comment]
Thanks for your interest in our work.

I noticed that this directory is the raw data downloaded from ScanNet. You should follow the [instruction](https://github.com/ScanNet/ScanNet/tree/master/SensReader/python) from the ScanNet repo to extract the images and poses.

Then you should follow the pre-process from the [MonoSDF](https://github.com/autonomousvision/monosdf/tree/main#custom-dataset) to extract the pseudo depth and pseudo normal.
Finally, running the [scannet2monosdf.py](https://github.com/shawLyu/Occ-SDF-Hybrid/blob/main/preprocess/scannet_to_monosdf.py) will generate the `cameras.npz` file.

**Comment by shawLyu** [comment]
If this issue has been solved, I will close it. 

Feel free to ask me more questions.

**Comment by saulgooodman** [comment]
I'm sorry, I'd like to confirm. 
I noticed that after preprocessing the data through the ScanNet official tutorial, there are two ways to obtain depth information:
 1) Depth and normals can be generated through the extract_monocular_cues.py in MonoSDF. 
2) Depth can also be generated through scannet_to_monosdf.py, which additionally produces cameras.npz. 
My question is whether the data used by OccSDF is first obtained through extract_monocular_cues.py to obtain depth and normals, and then later scannet_to_monosdf.py is used on the data preprocessed through the ScanNet official tutorial to obtain cameras.npz?
Thank you for your patience!

**Comment by shawLyu** [comment]
I understand the issue you're facing.

Within the extract_monocular_cues.py script, we aim to capitalize on Omnidata's capability to extract pseudo depth and pseudo normal, which will be utilized for subsequent reconstruction.

Regarding the scannet_to_monosdf.py script, it will employ the ground truth depth to rescale our scene into the unit sphere. However, it only produces the cameras.npz file and not the depth or normal information

**Comment by saulgooodman** [comment]
Hello, I followed the steps to customize the scannet dataset (it contains depth, normal, RGB data generated by omnidata, all of which are 384 * 384 size, and it also contains cameras.npz file generated by the scannet_to_monosdf, and I didn't do the operation of extracting a frame every 10 images), but I still have problems after running the code:

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

What is the reason for this problem? Is it related to the fact that I didn't extract a frame for every 10 images? Thank you for your patience!

**Comment by saulgooodman** [comment]
I also have another question about dataset processing. While reading the code, I noticed that the occSDF model can handle a maximum of 1024 images. Taking scene0000_01 from ScanNet as an example, is it correct to sample one image every 10 images for training? (Yesterday, I tried training with all frames from scene0000_01, and it took around 8 hours to train using a 2060 GPU). Thank you!

**Comment by shawLyu** [comment]
I'm sorry for not getting back to you sooner.  I got a cold recently.

You're correct in choosing to sample one image every 10 images to ensure the total count stays below 1024. If you need to process a larger number of images, you can indeed adjust the [embedding size](https://github.com/shawLyu/Occ-SDF-Hybrid/blob/c5b420dc07e67b1213473d09b481b7a46a5e143f/code/model/network.py#L383) at the specified link.

Regarding training time, your understanding is accurate for the MLP setting. If you're looking for faster training, the grid setting is a viable alternative. However, it's important to note that using the grid setting with the ScanNet configuration may result in an increased number of floaters.
