### ISSUE TITLE
About Normal C.

### ISSUE THREAD

**Issue by yiping-tks** [shawLyu/Occ-SDF-Hybrid#4]
hi, thanks for your great job, I wanna ask that what is Nomal C. in your code?

**Comment by shawLyu** [comment]
Thanks for your interest. 

I can not totally understand your question. Do you mean the normal_occ ?

This variable is the normal vector calculated from the occupancy field.

**Comment by yiping-tks** [comment]
Copy that!

**Comment by yiping-tks** [comment]
Oh, thanks for your reply! I mean the metric Normal Consistancy(Norm C.) you report in the paper on Replica dataset. Is it the normal_avg https://github.com/shawLyu/Occ-SDF-Hybrid/blob/c5b420dc07e67b1213473d09b481b7a46a5e143f/replica_eval/eval_recon.py#L177C3-L177C22

**Comment by shawLyu** [comment]
Yes, the meaning is the normal consistency. 
You can find more definitions of our matrics in the [supplemental file](https://openaccess.thecvf.com/content/ICCV2023/supplemental/Lyu_Learning_a_Room_ICCV_2023_supplemental.pdf).

**Comment by yiping-tks** [comment]
Ok, I get it, thanks a lot for your kind help!

**Comment by shawLyu** [comment]
It doesn't matter. 

I will close this issue.
