### ISSUE TITLE
How to extract mesh using OCC-SDF?

### ISSUE THREAD

**Issue by saulgooodman** [shawLyu/Occ-SDF-Hybrid#5]
Great work!
I have used your method to train a scene in replica dataset and got the model parameter dict.
I'd like to ask if there is way to use the pth file saved to extract mesh. I tried the eval.py in MonoSDF but it didn't work. You used hybrid geometry representation instead of simple SDF. So i'd like to ask which geometory representation did you use at last? OCC or SDF or in hybrid ways?
Thank you!

**Comment by shawLyu** [comment]
Sorry for the late reply.

The original training file indeed encompasses the [mesh extraction](https://github.com/shawLyu/Occ-SDF-Hybrid/blob/c5b420dc07e67b1213473d09b481b7a46a5e143f/code/utils/plots.py#L37) component, and the mesh is saved while the training is ongoing.

Just to clarify, the mesh extraction is specifically from the SDF field.

Are you suggesting that you prefer a separate script solely for extracting the mesh from the checkpoint?

If necessary, I can certainly push an additional file for this purpose.

**Comment by saulgooodman** [comment]
I have trained the model till the end(2000epoch)， but I haven’t seen the final extracted mesh. And I think it would be helpful to offer code to extract mesh from the checkpoint since the training progress can be visualized clearly. And it would be great if you can offer code to extract mesh from different fields so that the advantage of using SDF/OCC/hybrid representation can be seen clearly.
Thank you very much for your patience！

**Comment by shawLyu** [comment]
OK, I got it. 

I will try to upload this script before tomorrow.

Thanks for your suggestion.

**Comment by saulgooodman** [comment]
By the way, I extracted mesh and evaluated it with GT mesh. There is one other thing I'd like to confirm.
I noticed that the scale of the reconstructed mesh isn't aligned with the Ground Truth mesh. And the accuracy,completion evaluation result is 2.77 and 2.75 after 100 epochs, which is about 100 times bigger than the result from the paper (other testing metrics are OK). 
Is it because the paper uses meters as the unit, while the code uses centimeters as the unit? (the paper didn't declare the unit of 'acc' in the paper) Or is it because that there is something wrong with my preparation of data?
Thanks again for your patience!

**Comment by shawLyu** [comment]
I'm sorry for not getting back to you sooner. 

I have been busy rushing the paper for ECCV recently. Thus, I do not finish the script writing. 

Can you tell me which dataset you evaluated?

For the Scannet, the unit is the meter, and for the Replica the unit is the centimeter. You can refer to the comments [here](https://github.com/shawLyu/Occ-SDF-Hybrid/blob/cbf2eab783bd915e41d4af463382dae3db3c70e4/replica_eval/eval_recon.py#L170).

**Comment by saulgooodman** [comment]
Not to worry. Please feel free to prioritize your own research tasks.

I'll elaborate on the issue I encountered. I was testing on room0 of the Replica dataset. After running the tests, I noticed a significant difference in scale between the reconstructed mesh and the original mesh (with remarkably good detail reconstruction). I'd like to know if this is an issue with my dataset configuration or if it's something that can be ignored. （The reconstructed mesh VS ground truth mesh is shown as follows.）
![305ea415c827a7f6caa7b6e37f57d14](https://github.com/shawLyu/Occ-SDF-Hybrid/assets/91330822/fec13f78-6ce6-402a-8b38-84d6ac3548cc)


Also, I'd like to confirm if the accuracy metric used in the paper refers to centimeters (it wasn't specified in the paper). 

Thank you! Wishing you smooth submission to ECCV and successful acceptance!

**Comment by shawLyu** [comment]
I got it.

For scene-level reconstruction tasks, we usually normalize the scene into a unit sphere. Thus, the pre-processing script will calculate the scale matrix from the input camera pose. (Check [Scannet pre-processing script](https://github.com/shawLyu/Occ-SDF-Hybrid/blob/cbf2eab783bd915e41d4af463382dae3db3c70e4/preprocess/scannet_to_monosdf.py#L76))

This operation is because both hash-grid and position encoding work well in the range (-1,1). ( You can check the issues  or dataset tips from instant-ngp to get more information.)

So, we need to recover the scale of the reconstructed mesh by the [codes](https://github.com/shawLyu/Occ-SDF-Hybrid/blob/cbf2eab783bd915e41d4af463382dae3db3c70e4/replica_eval/cull_mesh.py#L52).
